const initalState = {
  user_data: [
    {
      Id: "id-1234",
      date: "2024.1.4",
      morning: [
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.4(1)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.4(1)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
      ],
      launch: [
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.4(2)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.4(2)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
      ],
      dinner: [
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.4(3)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.4(3)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
      ],
    },
    {
      Id: "id-1234",
      date: "2024.1.5",
      morning: [
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.5(1)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.5(1)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
      ],
      launch: [
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.5(2)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
      ],
      dinner: [
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품1.5(3)",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
        {
          id: "P000963-ZZ-AVG",
          foodCode: "P000963",
          dbBase: "가공식품",
          foodName: "가까운 목장의 신선한 원유로 만든 정일품",
          foodMaker: null,
          foodCategory: "강화우유",
          foodDetailCategory: "강화우유",
          foodServing: "200",
          foodUnit: "mL",
          foodCalorie: "140",
          protein: "8.0",
          fat: "5.4",
          syn: "10.0",
        },
      ],
    },
  ],
};

const userRedux = (state = initalState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};
export default userRedux;
